### ISSUE TITLE
Test Idea: The personal introduction card for the newcomer | Work book? 

### ISSUE THREAD

**Issue by tatianasheremet** [scholokov/long-travel-2#4011]
Hi! 
This is your personal card where you can track your progress, tasks, place important info etc 

To start with, check if you've completed all of the introduction steps: 

### Part 1. Introduction and get ready with the instruments

- [ ] Create an account in Github 
- [ ] Set up your account with your name and surname looking like  
              <img width="214" alt="Screenshot 2023-07-20 at 17 42 30" src="https://github.com/scholokov/long-travel-2/assets/57502593/dae85d59-c239-4ab0-8c3b-6d41bf9c8217">

- [ ] Downloaded and installed Slack from [here](https://slack.com/downloads/windows) 
- [ ] Entered the QAX team for the Travel Project [here](https://join.slack.com/t/qax-hq/shared_invite/zt-1avsyqlj8-M9coilQzVHVhGtSXaoYd7g)
- [ ] Texted @scholokov in Slack with the email that you used for your account in GitHub
- [ ] Accepted the invitation from the GitHub to join the Travel Project space  
- [ ] Texted one of PM's (@tatianasheremet or @ABatalov) in Slack with your GitHub nickname 
- [ ] Check that you're able to assign yourself to this task 

### Part 2. Get ready to practice 

- [ ] To get more information about the GitHub you can check the info [here](https://portal.qax-camp.com.ua/courses/github/)
- [ ] Take a look at the GitHub space for the Travel's Project [here](https://github.com/scholokov/long-travel-2/issues). Note the questions that may appear. 
- [ ] Take a look at the project that you'll be working on [here](https://long-travel.live/travels/)
- [ ] More about the project can be found on the educational portal [here](https://portal.qax-camp.com.ua/qax-8-0-travel-2-0/)
- [ ] Check your Google Calendar for scheduled meeting on each Wed at 18:00
- [ ] Before the closest Google Team Meeting on each Web at 18:30 check the workflow on the project [here](https://www.qax-camp.com.ua/courses/practise/lessons/workflow-project/)
- [ ] Prepare your questions and attend the team meeting on Wed 

### Part 3. Let's start the practice! 

- [ ] Here, in the very first comment in this task leave a comment in which collect all the links that you think might be useful 
- [ ] If you don't have an assigned task yet - remind @tatianasheremet or @ABatalov via Slack 
- [ ] Link the task assigned to you here in the comments
- [ ] Check the rules of creating the bug reports here (ТРЕБА НАПИСАТИ!!!)
- [ ] Remind yourself of the workflow on the project [here](https://www.qax-camp.com.ua/courses/practise/lessons/workflow-project/)
- [ ] If you don't know from where to start the testing of the travel check this for the ideas [here](https://drive.google.com/file/d/1bqe5TLGJ9k5_UGmQ_LBPEaxxXeo1hnKt/view)
- [ ]

**Comment by ABatalov** [comment]
@tatianasheremet it looks great )

**Comment by ABatalov** [comment]
Maybe better move this introduction card to the Code or Discussions pages?
